!THIS ROUTINE SAVES TRAJECTORIES FOR COMPUTING VEL - AUTOCORRELATION FUNCTIONS.
!THIS SUBROUTINE IS WRITTEN BY KALITH M ISMAIL, NOVEMBER-2022, NUS SINGAPORE.

    SUBROUTINE Vel()
        INCLUDE 'common.h'
        DIMENSION XVEL(NAN),YVEL(NAN),ZVEL(NAN)
       
        DO I = 1, NAN
           XVEL(I) = Q1D(1,I)/DELTA
           YVEL(I) = Q1D(2,I)/DELTA
           ZVEL(I) = Q1D(3,I)/DELTA
        ENDDO

!       DATA FOR THE VELOCITY AUTO-CORRELATION FUNCTION
        WRITE(16,708) TIME
        WRITE(16,707) (XVEL(I),YVEL(I),ZVEL(I),I=1,NAN)

708     FORMAT(F12.4)
707     FORMAT(3(50F9.6,1x))

        RETURN
    END SUBROUTINE Vel

